# render.yaml
services:
  - type: web
    name: collaboration-platform
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
      dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: collaboration_platform
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ENABLE_AI
        value: false
      - key: LOG_LEVEL
        value: warn
    healthCheckPath: /api/health
    numInstances: 1

databases:
  - name: collaboration_platform
    plan: free
    databaseName: collaboration_platform
    user: collaboration_platform_user