# render.yaml
services:
  - type: web
    name: collaboration-platform
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
      dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: collaboration_platform
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: PORT
        value: 4000
    healthCheckPath: /api/health